version: 0.2

env:
  variables:
    NODE_ENV: "development"

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm run-script build
      
artifacts:
  files:
    - '**/*'
  base-directory: build
cache:
  paths:
    - './node_modules/**/*'
