version: 0.2

env:
  variables:
    NODE_ENV: "development"

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install -g jest
      - npm install -g gatsby

  pre_build:
    commands:
      - npm install

  build:
    commands:
      - npm build

cache:
  paths:
    - './node_modules/**/*'